In [50]:
%%capture
%load_ext autoreload
%autoreload 2

In [51]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.preprocessing import LabelEncoder
from recsys_pipeliner.recommendations.transformer import (
    SimilarityTransformer,
    UserItemMatrixTransformer,
)
from recsys_pipeliner.algorithms.recommenders import ItemBasedCFRecommender
from IPython.display import display
from recsys_pipeliner.evaluation import (
    AccuracyMetrics,
    AlgorithmEvaluator,
    EvaluationDataset,
    TopNMetrics,
)
from IPython.display import display

In [52]:
# load test data
ratings_data_types = {"user_id": str, "item_id": str, "rating": np.float64}
user_item_ratings_df = pd.read_csv(
    "../../tests/test_data/user_item_ratings_toy.csv", dtype=ratings_data_types
)
item_features_df = pd.read_csv(
    "../../tests/test_data/item_features_toy.csv", index_col=0
)

display(user_item_ratings_df.head(3))
display(item_features_df.head(3))

  user_id item_id  rating
0  U00001  I00024     0.8
1  U00001  I00013     0.6
2  U00001  I00005     1.0

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10
I00001,0.65,0.71,0.75,0.91,0.70,0.75,0.88,0.95,0.62,0.87
I00002,0.57,0.56,0.14,0.33,0.39,0.29,0.17,0.13,0.11,0.60
I00003,0.46,0.65,0.51,0.69,0.47,0.49,0.49,0.59,0.68,0.72

In [53]:
# encode the user/item ids
item_encoder = LabelEncoder()
user_encoder = LabelEncoder()

user_item_ratings_df["item_id"] = item_encoder.fit_transform(user_item_ratings_df["item_id"])
user_item_ratings_df["user_id"] = user_encoder.fit_transform(user_item_ratings_df["user_id"])

user_item_ratings_np = user_item_ratings_df.to_numpy()

unique_users = pd.Series(user_encoder.classes_)
unique_items = pd.Series(item_encoder.classes_)

print("unique_users", unique_users.shape[0])
print("unique_items", unique_items.shape[0])

unique_users 12
unique_items 24

In [54]:
dataset = EvaluationDataset(
    user_item_ratings_np, 
    min_user_ratings=2, 
    min_item_ratings=2, 
    random_seed=42
)
trainset, testset = dataset.trainset, dataset.testset
anti_testset = dataset.anti_testset
usable_ratings = dataset.usable

print("user_item_ratings_np", user_item_ratings_np.shape)
print("trainset", trainset.shape)
print("testset", testset.shape)
print("anti_testset", anti_testset.shape)
print("usable_ratings", usable_ratings.shape)

assert set(np.unique(trainset[:, 0]).astype(int)) == set(unique_users.index)
assert (
    set(np.unique(testset[:, 0]).astype(int)) == set(unique_users.index)
)

user_item_ratings_np (96, 3)
trainset (84, 3)
testset (12, 3)
anti_testset (192, 2)
usable_ratings (96, 3)

In [55]:
# create the user/item matrix
user_item_matrix_transformer = UserItemMatrixTransformer()

user_item_matrix = user_item_matrix_transformer.transform(
    trainset,
)
print("user_item_matrix", user_item_matrix.shape)

# sanity check
users = trainset[:, 0].astype(int)
items = trainset[:, 1].astype(int)
ratings = trainset[:, 2].astype(np.float32)
for user, item, rating in zip(users, items, ratings):
    assert user_item_matrix[user, item] == rating

user_item_matrix (12, 24)

In [56]:
users = anti_testset[:, 0]
items = anti_testset[:, 1]

# sanity check
for user, item in anti_testset:
    assert user_item_matrix[user, item] == 0

In [57]:
rec = ItemBasedCFRecommender(k=5, n=5)
evaluator = AlgorithmEvaluator(rec)

result = evaluator.evaluate(
    user_item_matrix, dataset.testset, dataset.anti_testset, top_n=5
)

result

(AccuracyMetrics(rmse=0.3305, mae=0.2694),
 TopNMetrics(HR=0.25, cHR=0.25, ARHR=0.083333))

In [ ]:
# sense check results

# TODO: this seems to be wrong? 
# Need to go back and confirm expected recommendations and predictions manually.
# Not sure if the unit tests validation data is correct.

rec2 = ItemBasedCFRecommender(k=5, n=5)
rec2.fit(user_item_matrix)
test_input = dataset.testset[:, 0:2].astype(np.int32)
test_predictions = dataset.testset[:, 2]

recommendations = rec2.recommend(test_input)

for u, rec in zip(test_input[:, 0], recommendations):
    us = np.repeat(u, len(rec))
    pred_input = np.column_stack((us, rec))
    prediction = rec2.predict(pred_input)
    results = np.column_stack((pred_input, prediction))
    print(results)

[[ 0.          8.          0.2       ]
 [ 0.         18.          0.46693999]
 [ 0.         16.          0.235594  ]
 [ 0.         21.          0.44581199]
 [ 0.          1.          0.59200698]]
[[ 1.         10.          0.72965997]
 [ 1.          5.          0.72856498]
 [ 1.          3.          0.64856899]
 [ 1.         20.          0.69782197]
 [ 1.         22.          0.70173001]]
[[ 2.          4.          0.92676699]
 [ 2.          0.          0.971084  ]
 [ 2.          6.          0.74086702]
 [ 2.         20.          0.86920202]
 [ 2.         12.          0.739851  ]]
[[ 3.         19.          0.63503599]
 [ 3.         22.          0.56914502]
 [ 3.          4.          0.65936399]
 [ 3.          9.          0.68295401]
 [ 3.         18.          0.558806  ]]
[[ 4.          6.          0.78526503]
 [ 4.          2.          0.72854197]
 [ 4.         10.          0.742688  ]
 [ 4.         22.          0.489889  ]
 [ 4.         23.          0.68590999]]
[[ 5.         16.          0.48851001]
 [ 5.         17.          0.64911598]
 [ 5.         14.          0.51393902]
 [ 5.         21.          0.44070101]
 [ 5.          2.          0.58361399]]
[[ 6.         16.          0.53824598]
 [ 6.         17.          0.64141798]
 [ 6.         13.          0.52569503]
 [ 6.          2.          0.60539198]
 [ 6.         10.          0.63476402]]
[[ 7.         12.          0.95007002]
 [ 7.         10.          0.90978801]
 [ 7.          4.          0.97814602]
 [ 7.          2.          0.92055601]
 [ 7.         20.          0.78424799]]
[[ 8.         10.          0.81370997]
 [ 8.          2.          0.88      ]
 [ 8.         20.          0.88      ]
 [ 8.         19.          0.36449799]
 [ 8.         21.          0.70920599]]
[[ 9.         19.          0.28999999]
 [ 9.          1.          0.336032  ]
 [ 9.         13.          0.44213599]
 [ 9.         15.          0.45997399]
 [ 9.         12.          0.374345  ]]
[[10.         14.          0.63637   ]
 [10.         16.          0.65673   ]
 [10.          9.          0.64474702]
 [10.          5.          0.81946999]
 [10.          3.          0.77862298]]
[[11.         17.          0.387932  ]
 [11.         19.          0.616032  ]
 [11.         12.          0.597812  ]
 [11.          6.          0.46743801]
 [11.          5.          0.47420001]]

# Hybrid Recommender

This recommender uses item features to calcuate similarity and user/item ratings to rank recommendations.

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

# Content-based filtering and a hybrid recommender

item_features_np = item_features_df.to_numpy().astype(np.float32)

# NOTE: this is the only difference to how the ItemBasedCFRecommender is implemented.
# We just use the item features to calculate item similarity.
item_similarity_matrix = cosine_similarity(item_features_np).astype(np.float32).round(6)



predictions = []

for user_idx, item_idx in anti_testset:
    _, target_user_rated_items, target_user_ratings = sp.sparse.find(
        user_item_matrix[user_idx, :]
    )

    # exclude item_idx if already rated by target user
    target_user_rated_items = target_user_rated_items[target_user_rated_items != item_idx]
    users_ratings = target_user_ratings[target_user_rated_items != item_idx]

    # get the item similarities to item_idx
    item_similarities = (
        item_similarity_matrix[:, target_user_rated_items][item_idx]
        .astype(np.float32)
        .round(6)
    )
    k = 5
    # sort by similarity (desc) and get top k
    top_k_mask = np.argsort(1 - item_similarities)[:k]
    top_k_target_user_ratings = users_ratings[top_k_mask]
    top_k_rated_item_similarities = item_similarities[top_k_mask]
    # weighted average rating
    prediction = (
        np.average(top_k_target_user_ratings, axis=0, weights=top_k_rated_item_similarities)
        .astype(np.float32)
        .round(6)
    )
    predictions.append([user_idx, item_idx, prediction])

predictions

[[0, 0, 0.63807],
 [0, 1, 0.638394],
 [0, 2, 0.63852],
 [0, 3, 0.64014],
 [0, 5, 0.482618],
 [0, 6, 0.640523],
 [0, 7, 0.602654],
 [0, 8, 0.637624],
 [0, 9, 0.640147],
 [0, 13, 0.595282],
 [0, 15, 0.638849],
 [0, 16, 0.636553],
 [0, 18, 0.640008],
 [0, 19, 0.717574],
 [0, 20, 0.640535],
 [0, 21, 0.640334],
 [1, 0, 0.760667],
 [1, 1, 0.765463],
 [1, 3, 0.763056],
 [1, 4, 0.761822],
 [1, 5, 0.728877],
 [1, 6, 0.762332],
 [1, 7, 0.732235],
 [1, 8, 0.759856],
 [1, 9, 0.761205],
 [1, 10, 0.761991],
 [1, 12, 0.762343],
 [1, 15, 0.761501],
 [1, 19, 0.76472],
 [1, 20, 0.761425],
 [1, 22, 0.76287],
 [1, 23, 0.761576],
 [2, 0, 0.851657],
 [2, 1, 0.852841],
 [2, 4, 0.851584],
 [2, 6, 0.85222],
 [2, 7, 0.852086],
 [2, 8, 0.851606],
 [2, 9, 0.8521],
 [2, 11, 0.853226],
 [2, 12, 0.851334],
 [2, 14, 0.851448],
 [2, 16, 0.850871],
 [2, 17, 0.853542],
 [2, 19, 0.849565],
 [2, 20, 0.851885],
 [2, 21, 0.852543],
 [2, 22, 0.85119],
 [3, 1, 0.585239],
 [3, 2, 0.584808],
 [3, 4, 0.583762],
 [3, 5, 0.583467],
 [3, 6, 0.585584],
 [3, 8, 0.584324],
 [3, 9, 0.584066],
 [3, 11, 0.583884],
 [3, 13, 0.586865],
 [3, 16, 0.583922],
 [3, 17, 0.581737],
 [3, 18, 0.583665],
 [3, 19, 0.510441],
 [3, 20, 0.58479],
 [3, 21, 0.585718],
 [3, 22, 0.583017],
 [4, 0, 0.597333],
 [4, 2, 0.598033],
 [4, 3, 0.596615],
 [4, 4, 0.671049],
 [4, 5, 0.59759],
 [4, 6, 0.596003],
 [4, 7, 0.592881],
 [4, 8, 0.598125],
 [4, 10, 0.596062],
 [4, 11, 0.521612],
 [4, 12, 0.594177],
 [4, 16, 0.596731],
 [4, 17, 0.670614],
 [4, 18, 0.595026],
 [4, 22, 0.59324],
 [4, 23, 0.591213],
 [5, 0, 0.687972],
 [5, 1, 0.691285],
 [5, 2, 0.686928],
 [5, 3, 0.686799],
 [5, 4, 0.687912],
 [5, 5, 0.647688],
 [5, 6, 0.687526],
 [5, 8, 0.687105],
 [5, 10, 0.686505],
 [5, 14, 0.689698],
 [5, 15, 0.685962],
 [5, 16, 0.689766],
 [5, 17, 0.648348],
 [5, 20, 0.68745],
 [5, 21, 0.685465],
 [5, 23, 0.693629],
 [6, 0, 0.660021],
 [6, 1, 0.658444],
 [6, 2, 0.659852],
 [6, 3, 0.659592],
 [6, 4, 0.659902],
 [6, 5, 0.661501],
 [6, 8, 0.659158],
 [6, 9, 0.659711],
 [6, 10, 0.659622],
 [6, 12, 0.661179],
 [6, 13, 0.683857],
 [6, 16, 0.660096],
 [6, 17, 0.620497],
 [6, 18, 0.660194],
 [6, 19, 0.770491],
 [6, 22, 0.661098],
 [7, 0, 0.878745],
 [7, 2, 0.855202],
 [7, 3, 0.855907],
 [7, 4, 0.880792],
 [7, 5, 0.855187],
 [7, 9, 0.855635],
 [7, 10, 0.855955],
 [7, 11, 0.881728],
 [7, 12, 0.85553],
 [7, 13, 0.880438],
 [7, 15, 0.879086],
 [7, 16, 0.856434],
 [7, 19, 0.881073],
 [7, 20, 0.856059],
 [7, 21, 0.879717],
 [7, 23, 0.878485],
 [8, 2, 0.640564],
 [8, 3, 0.639789],
 [8, 5, 0.6365],
 [8, 6, 0.640125],
 [8, 7, 0.661049],
 [8, 8, 0.640068],
 [8, 10, 0.6401],
 [8, 11, 0.665865],
 [8, 13, 0.641693],
 [8, 14, 0.638848],
 [8, 16, 0.640257],
 [8, 17, 0.639516],
 [8, 18, 0.640164],
 [8, 19, 0.639945],
 [8, 20, 0.641093],
 [8, 21, 0.642137],
 [9, 0, 0.522841],
 [9, 1, 0.536388],
 [9, 3, 0.527307],
 [9, 4, 0.526946],
 [9, 6, 0.526191],
 [9, 7, 0.482322],
 [9, 8, 0.521805],
 [9, 12, 0.524113],
 [9, 13, 0.520069],
 [9, 14, 0.413128],
 [9, 15, 0.525542],
 [9, 18, 0.522558],
 [9, 19, 0.525468],
 [9, 20, 0.411458],
 [9, 21, 0.526028],
 [9, 23, 0.51738],
 [10, 0, 0.799564],
 [10, 1, 0.798734],
 [10, 3, 0.800182],
 [10, 4, 0.780264],
 [10, 5, 0.801189],
 [10, 6, 0.799586],
 [10, 7, 0.794044],
 [10, 8, 0.799316],
 [10, 9, 0.799848],
 [10, 11, 0.781314],
 [10, 12, 0.840589],
 [10, 14, 0.800247],
 [10, 16, 0.839876],
 [10, 18, 0.780564],
 [10, 19, 0.841604],
 [10, 23, 0.840902],
 [11, 0, 0.394313],
 [11, 2, 0.393179],
 [11, 3, 0.391767],
 [11, 4, 0.390696],
 [11, 5, 0.50753],
 [11, 6, 0.392191],
 [11, 9, 0.392883],
 [11, 10, 0.39287],
 [11, 12, 0.393193],
 [11, 15, 0.392852],
 [11, 17, 0.510849],
 [11, 19, 0.392604],
 [11, 20, 0.393567],
 [11, 21, 0.392077],
 [11, 22, 0.392971],
 [11, 23, 0.432941]]